aligned bindingdb
RobokopU24/ORION pull request #181
Opened 2023-09-15 19:42 UTC by cbizon

* Modified the edge granularity to be chemical/target/measure_type.  This means that it's ok to average the affinities into a single number
* Simplified the affinities into a single list
* Provided an average affinity
* Pulled the publications into a single place
* removed patent and aid from the publications: these are not specific to the edge but are really features of the assay
* Changed the predicates from just binds to increases/decreases activity where appropriate
* Changed handling of >,< and 0 affinities.

2023-09-15 20:06 UTC, beasleyjonm requested changes
I think changing the pIC50 and pEC50 measurement predicates to increase/decreases activity of is fair, but I am still quite uncomfortable with saying that pKi infers that the protein's activity is decreased. I just found several examples of known GPCR agonists in bindingdb reporting pKi, so to say they decrease activity would be innaccurate. I'd suggest changing the "measure_to_predicate" dictionary back to "binds" for pKi.
I am also unsure that we'd want to separate out k_on and k_off as their own measurements with their own edges. These are just rate terms used to calculate Kd/Ki so each row with a k_on/k_off value already has another measurement type in the row, and that other measurement has far more value.

2023-09-15 20:42 UTC, cbizon commented
@beasleyjonm can you show those examples?  Is it because the agonists are binding in a competitive inhibition assay or something?

2023-09-15 22:49 UTC, beasleyjonm commented
> @beasleyjonm can you show those examples? Is it because the agonists are binding in a competitive inhibition assay or something?

[pKi_agonists_BindingDB.csv](https://github.com/RobokopU24/ORION/files/12629199/pKi_agonists_BindingDB.csv)
Sure thing! In the attached file I have some examples of GPCR agonists with BindingDB edges, many of which have just pKi reported. This was from the first pass at making a BindingDB parser, so the publications attribute is messed up, but the measurement data should all be the same.
It's probably possible to do some more complicated assignment of predicates by looking at assay description text or by considering the protein family and the types of measurements typically reported for it, but that might be a tough endeavor.

2023-09-18 17:12 UTC, beasleyjonm approved these changes

2023-09-18 17:12 UTC, merged