Modified predicates affected by biolink:binds
RobokopU24/ORION pull request #232
Opened 2024-07-10 16:34 UTC by eKathleenCarter

Modified predicates to remove depreciated predict biolink:binds. Added comments for future modifications in /Common/predicates.py

2024-07-11 13:24 UTC, cbizon commented on Common/predicates.py
> +    "ed50": f"RO:0002434",  # Effective Dose. Potentially needs to be {DGIDB}:agonist
ED50 tells you about the therapeutic effect, so it doesn't really say much about whether it is an agonist or antagonist.  In fact, it's probably not even relevant to a chemical/protein edge but should be on a chemical/phenotpyicfeature or chemical/disease edge

2024-07-11 13:24 UTC, cbizon commented on Common/predicates.py
> +    "gi50": f"RO:0002434",  # Growth Inhibitor. Potentially needs to be {DGIDB}:agonist
{DGIDB}:Inhibitor?

2024-07-11 13:25 UTC, cbizon commented on Common/predicates.py
> +    "interacts_with": f"{DRUGBANK}:target",  # maps to biolink:physically_interacts_with
I think target has a more specific meaning - that it's a therapeutic target. Interacts_with is a lot weaker just saying that the chemical interacts with the protein.  Since 2434 is "interacts with" I think I'd leave this one.

2024-07-11 13:26 UTC, cbizon requested changes
Made a few comments

2024-07-11 14:18 UTC, eKathleenCarter commented on Common/predicates.py
> +    "interacts_with": f"{DRUGBANK}:target",  # maps to biolink:physically_interacts_with
RO:0002434 is "interacts with" in the ontology 

However:
biolink model look up maps RO:0002434 to biolink:related_to 

The biolink-model.yaml maps RO:0002434 to biolink:affects as a narrow mapping

SEMMEDDB:INTERACTS_WITH is the only predicate that maps to biolink:interacts_with in the current biolink model
https://biolink.github.io/biolink-model/interacts_with/

biolink:phyiscally_interacts_with has more maps (including drugbank:target)
https://biolink.github.io/biolink-model/physically_interacts_with/

2024-07-11 14:20 UTC, eKathleenCarter commented on Common/predicates.py
> +    "ed50": f"RO:0002434",  # Effective Dose. Potentially needs to be {DGIDB}:agonist
my logic is that ec50 and ed50 are essentially the same (in vitro vs in vivo measurement). If we have ec50 as agonist, do we not want ed50 to be agonist as well?

2024-07-11 14:22 UTC, eKathleenCarter commented on Common/predicates.py
> +    "gi50": f"RO:0002434",  # Growth Inhibitor. Potentially needs to be {DGIDB}:agonist
agreed

2024-07-11 16:35 UTC, cbizon commented on Common/predicates.py
> +    "ed50": f"RO:0002434",  # Effective Dose. Potentially needs to be {DGIDB}:agonist
Not necessarily, because we don't know the relationship between the in vitro and in vivo measurement.  An EC50 is typically what is measured in an agonist or stimulator assay. So if you have a good EC50, you are increasing the activity of the relevant protein, and if you have a good IC50 you are decreasing it.

The ED50 is totally phenotypic - it's all about the downstream effect.  But that effect can be very downstream and go through all kinds of signal regulation. So for different components in the upstream pathway sometimes you want them to be agonists to produce the effect, and sometimes you want them to be antagonists, depending on the role that they play in the pathways.  

But I guess the main point is that it makes no sense to have an ed50 between a chemical and a gene/protein.  Is it possible to see whether we actually have any of these?

2024-07-11 18:42 UTC, cbizon commented on Common/predicates.py
> +    "interacts_with": f"{DRUGBANK}:target",  # maps to biolink:physically_interacts_with
Hmm, 2434 is tricky because its definition is "A relationship that holds between two entities in which the processes executed by the two entities are causally connected."   But in biolink physically_interacts_with (and therefore interacts_with) does not imply a causal relation.  So it makes sense for them not to be equivalent.

I guess it would be easier to be sure if we know the context in which "interacts-with" was found in our ingestss.

(but I'd be tempted to put 2436 for this one)

2024-07-16 16:43 UTC, eKathleenCarter commented on Common/predicates.py
> +    "gi50": f"RO:0002434",  # Growth Inhibitor. Potentially needs to be {DGIDB}:agonist
resolved in changes made to predicates.py

2024-07-16 17:15 UTC, cbizon approved these changes

2024-07-19 18:38 UTC, EvanDietzMorris approved these changes

2024-07-19 18:38 UTC, merged